"""Synthetic rich-media generation and validation for the GPU demo."""

from __future__ import annotations

import json
import shlex
import subprocess
from fractions import Fraction
from pathlib import Path
from typing import Any

from ai_media.demo import DemoError
from ai_media.demo.config import DEMO_FRAMES, DemoPaths, DemoVideoContract


def write_demo_media_assets(paths: DemoPaths) -> None:
    """Write the small subtitle, attachment, and chapter metadata fixtures."""
    paths.subtitle.parent.mkdir(parents=True, exist_ok=True)
    paths.subtitle.write_text(
        "1\n00:00:00,000 --> 00:00:00,900\nAI Media Enhancer demo\n",
        encoding="utf-8",
    )
    paths.attachment.write_text(
        "Generated by the ai-media-enhancer self-contained demo.\n",
        encoding="utf-8",
    )
    paths.metadata.write_text(
        """;FFMETADATA1
title=AI Media Enhancer Demo
comment=Generated synthetic input
[CHAPTER]
TIMEBASE=1/1000
START=0
END=500
title=First half
[CHAPTER]
TIMEBASE=1/1000
START=500
END=1000
title=Second half
""",
        encoding="utf-8",
    )


def build_demo_input_command(paths: DemoPaths) -> list[str]:
    """Build a deterministic rich 720p MKV fixture."""
    x264_params = (
        "keyint=24:min-keyint=24:scenecut=0:bframes=0:"
        "colorprim=bt709:transfer=bt709:colormatrix=bt709:range=limited"
    )
    return [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-y",
        "-f",
        "lavfi",
        "-i",
        "testsrc2=size=1280x720:rate=24:duration=1",
        "-f",
        "lavfi",
        "-i",
        "sine=frequency=440:sample_rate=48000:duration=1",
        "-f",
        "lavfi",
        "-i",
        "sine=frequency=880:sample_rate=48000:duration=1",
        "-i",
        str(paths.subtitle),
        "-f",
        "ffmetadata",
        "-i",
        str(paths.metadata),
        "-map",
        "0:v:0",
        "-map",
        "1:a:0",
        "-map",
        "2:a:0",
        "-map",
        "3:s:0",
        "-map_metadata",
        "4",
        "-map_chapters",
        "4",
        "-frames:v",
        str(DEMO_FRAMES),
        "-c:v",
        "libx264",
        "-preset",
        "fast",
        "-pix_fmt",
        "yuv420p",
        "-x264-params",
        x264_params,
        "-color_range",
        "tv",
        "-colorspace",
        "bt709",
        "-color_trc",
        "bt709",
        "-color_primaries",
        "bt709",
        "-c:a",
        "aac",
        "-b:a",
        "96k",
        "-c:s",
        "srt",
        "-metadata:s:a:0",
        "language=eng",
        "-metadata:s:a:1",
        "language=jpn",
        "-disposition:a:0",
        "default",
        "-disposition:a:1",
        "0",
        "-disposition:s:0",
        "forced",
        "-attach",
        str(paths.attachment),
        "-metadata:s:t:0",
        "mimetype=text/plain",
        "-metadata:s:t:0",
        f"filename={paths.attachment.name}",
        str(paths.input_video),
    ]


def _run_json(command: list[str]) -> dict[str, Any]:
    try:
        result = subprocess.run(command, check=True, capture_output=True, text=True)
        value = json.loads(result.stdout)
    except (OSError, subprocess.CalledProcessError, json.JSONDecodeError) as exc:
        raise DemoError(f"cannot inspect demo output: {shlex.join(command)}") from exc
    if not isinstance(value, dict):
        raise DemoError("ffprobe returned a non-object JSON value")
    return value


def _probe_video(path: Path) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    probe = _run_json(
        [
            "ffprobe",
            "-v",
            "error",
            "-count_frames",
            "-show_streams",
            "-show_chapters",
            "-show_format",
            "-of",
            "json",
            str(path),
        ]
    )
    packet_probe = _run_json(
        [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_packets",
            "-show_entries",
            "packet=pts,dts,flags",
            "-of",
            "json",
            str(path),
        ]
    )
    packets = packet_probe.get("packets", [])
    if not isinstance(packets, list):
        raise DemoError("ffprobe packets field is not a list")
    return probe, packets


def _strictly_increasing(packets: list[dict[str, Any]], key: str) -> bool:
    previous: int | None = None
    for packet in packets:
        try:
            current = int(packet[key])
        except (KeyError, TypeError, ValueError):
            return False
        if previous is not None and current <= previous:
            return False
        previous = current
    return True


def _stream_inventory(
    streams: list[dict[str, Any]],
    errors: list[str],
) -> dict[str, list[dict[str, Any]]]:
    by_type = {
        stream_type: [
            stream for stream in streams if stream.get("codec_type") == stream_type
        ]
        for stream_type in ("video", "audio", "subtitle", "attachment")
    }
    expected_counts = {"video": 1, "audio": 2, "subtitle": 1, "attachment": 1}
    for stream_type, expected_count in expected_counts.items():
        if len(by_type[stream_type]) != expected_count:
            errors.append(
                f"{stream_type} stream count: expected {expected_count}, "
                f"got {len(by_type[stream_type])}"
            )
    return by_type


def _validate_video_stream(
    video: dict[str, Any],
    packets: list[dict[str, Any]],
    contract: DemoVideoContract,
    errors: list[str],
) -> None:
    expected_video: dict[str, object] = {
        "codec_name": "h264",
        "width": contract.width,
        "height": contract.height,
        "pix_fmt": "yuv420p",
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "has_b_frames": 0,
    }
    for key, expected_value in expected_video.items():
        if video.get(key) != expected_value:
            errors.append(f"{key}: expected {expected_value!r}, got {video.get(key)!r}")

    try:
        actual_fps = Fraction(
            str(video.get("avg_frame_rate") or video.get("r_frame_rate"))
        )
    except (TypeError, ValueError, ZeroDivisionError):
        actual_fps = Fraction(0, 1)
    if actual_fps != Fraction(contract.fps):
        errors.append(f"fps: expected {contract.fps}, got {actual_fps}")

    frame_count = video.get("nb_read_frames") or video.get("nb_frames")
    if str(frame_count) != str(contract.frames):
        errors.append(f"frame count: expected {contract.frames}, got {frame_count}")
    if len(packets) != contract.frames:
        errors.append(f"packet count: expected {contract.frames}, got {len(packets)}")
    if not _strictly_increasing(packets, "pts"):
        errors.append("video PTS are not strictly increasing")
    if not _strictly_increasing(packets, "dts"):
        errors.append("video DTS are not strictly increasing")
    if not packets or "K" not in str(packets[0].get("flags", "")):
        errors.append("first video packet is not a keyframe")


def _validate_auxiliary_media(
    probe: dict[str, Any],
    by_type: dict[str, list[dict[str, Any]]],
    errors: list[str],
) -> None:
    chapters = probe.get("chapters", [])
    if not isinstance(chapters, list) or len(chapters) != 2:
        errors.append(f"chapter count: expected 2, got {len(chapters) if chapters else 0}")
    else:
        chapter_titles = [chapter.get("tags", {}).get("title") for chapter in chapters]
        if chapter_titles != ["First half", "Second half"]:
            errors.append(f"chapter titles differ: {chapter_titles!r}")

    format_tags = {
        key.lower(): value
        for key, value in probe.get("format", {}).get("tags", {}).items()
    }
    if format_tags.get("title") != "AI Media Enhancer Demo":
        errors.append("global title metadata was not preserved")
    if format_tags.get("comment") != "Generated synthetic input":
        errors.append("global comment metadata was not preserved")

    if len(by_type["audio"]) == 2:
        languages = [
            stream.get("tags", {}).get("language") for stream in by_type["audio"]
        ]
        if languages != ["eng", "jpn"]:
            errors.append(f"audio language tags differ: {languages!r}")
        dispositions = [
            stream.get("disposition", {}).get("default") for stream in by_type["audio"]
        ]
        if dispositions != [1, 0]:
            errors.append(f"audio dispositions differ: {dispositions!r}")
    if len(by_type["subtitle"]) == 1:
        forced = by_type["subtitle"][0].get("disposition", {}).get("forced")
        if forced != 1:
            errors.append("subtitle forced disposition was not preserved")
    if len(by_type["attachment"]) == 1:
        attachment_tags = by_type["attachment"][0].get("tags", {})
        if attachment_tags.get("filename") != "attachment.txt":
            errors.append("attachment filename was not preserved")
        if attachment_tags.get("mimetype") != "text/plain":
            errors.append("attachment MIME type was not preserved")


def validate_demo_probe(
    probe: dict[str, Any],
    packets: list[dict[str, Any]],
    contract: DemoVideoContract,
) -> dict[str, Any]:
    """Validate the video and rich-media contract from parsed FFprobe data."""
    errors: list[str] = []
    streams = probe.get("streams", [])
    if not isinstance(streams, list):
        streams = []
    by_type = _stream_inventory(streams, errors)
    video = by_type["video"][0] if len(by_type["video"]) == 1 else {}
    _validate_video_stream(video, packets, contract, errors)
    _validate_auxiliary_media(probe, by_type, errors)

    if errors:
        raise DemoError("demo media validation failed:\n- " + "\n- ".join(errors))
    return {
        "width": contract.width,
        "height": contract.height,
        "fps": contract.fps,
        "frames": contract.frames,
        "stream_counts": {
            "video": 1,
            "audio": 2,
            "subtitle": 1,
            "attachment": 1,
        },
        "chapters": 2,
        "timestamps": "strictly_monotonic",
    }


def validate_demo_video(path: Path, contract: DemoVideoContract) -> dict[str, Any]:
    """Fully decode and validate one demo input/output."""
    try:
        subprocess.run(
            [
                "ffmpeg",
                "-v",
                "error",
                "-xerror",
                "-i",
                str(path),
                "-map",
                "0:v",
                "-map",
                "0:a?",
                "-f",
                "null",
                "-",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise DemoError(f"full decode failed for {path}") from exc
    probe, packets = _probe_video(path)
    return validate_demo_probe(probe, packets, contract)
