"""Issue-ready model compatibility report assembly."""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Any, Literal
from urllib.parse import urlsplit

from trtvideo.compatibility.evidence import (
    CompatibilityEvidenceError,
    command_evidence,
    conformance_evidence,
    engine_evidence,
    file_identity,
    public_value,
)
from trtvideo.compatibility.media import (
    CompatibilityMediaError,
    inspect_media,
    validate_media,
)
from trtvideo.diagnostics.doctor import DoctorReport, run_doctor

REPORT_SCHEMA_VERSION = 1
_MAX_ISSUE_BODY_BYTES = 60 * 1024
SourceFormat = Literal["checkpoint", "onnx"]


@dataclass(frozen=True)
class CompatibilityRequest:
    """Inputs required to bind one community compatibility report."""

    model_name: str
    model_source: str
    model_license: str
    source_format: SourceFormat
    source_artifact: Path
    engine: Path
    input_video: Path
    output_video: Path
    expected_frames: int
    commands_file: Path
    export_conformance: Path | None
    image_reference: str
    gpu_id: int
    output_dir: Path


def _package_version() -> str:
    try:
        return version("trtvideo")
    except PackageNotFoundError:
        return "unknown"


def _doctor_evidence(report: DoctorReport) -> dict[str, Any]:
    checks = []
    for check in report.checks:
        detail = check.detail
        if check.component == "Disk" and " at " in detail:
            detail = detail.split(" at ", 1)[0]
        try:
            detail = public_value(detail, f"Doctor {check.component} detail")
        except CompatibilityEvidenceError:
            detail = "[redacted unsafe diagnostic detail]"
        checks.append(
            {
                "component": check.component,
                "passed": check.passed,
                "detail": detail,
            }
        )
    return {"ready": report.ready, "checks": checks}


def _image_evidence(reference: str) -> tuple[dict[str, str], list[str]]:
    raw_image = {
        "reference": reference,
        "package_version": _package_version(),
        "repository_revision": os.environ.get("TRTVIDEO_BUILD_REVISION", "unknown"),
        "source_dirty": os.environ.get("TRTVIDEO_BUILD_DIRTY", "unknown"),
        "base_reference": os.environ.get("TRTVIDEO_BASE_IMAGE", "unknown"),
    }
    image: dict[str, str] = {}
    errors: list[str] = []
    for field, value in raw_image.items():
        try:
            image[field] = public_value(value, f"Image {field}")
        except CompatibilityEvidenceError as exc:
            image[field] = "[omitted]"
            errors.append(str(exc))
    if image["reference"] in {"", "unknown"}:
        errors.append("Image reference is required")
    if re.fullmatch(r"[0-9a-f]{40}|[0-9a-f]{64}", image["repository_revision"]) is None:
        errors.append("Container image has no repository revision")
    if image["source_dirty"] != "0":
        errors.append("Container image must be built from a clean source revision")
    if image["base_reference"] in {"", "unknown"}:
        errors.append("Container image has no base image reference")
    if image["package_version"] in {"", "unknown"}:
        errors.append("Container image has no installed package version")
    return image, errors


def _public_url(value: str, label: str) -> str:
    normalized = public_value(value, label)
    try:
        parsed = urlsplit(normalized)
    except ValueError as exc:
        raise CompatibilityEvidenceError(f"{label} must be a valid public URL") from exc
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise CompatibilityEvidenceError(f"{label} must be a public HTTP(S) URL")
    if parsed.username is not None or parsed.password is not None:
        raise CompatibilityEvidenceError(f"{label} must not contain URL credentials")
    return normalized


def _json_block(value: Any) -> str:
    return "```json\n" + json.dumps(value, indent=2, sort_keys=True) + "\n```"


def render_issue_markdown(report: dict[str, Any]) -> str:
    """Render a complete GitHub issue body from sanitized report data."""
    model = report["model"]
    lines = [
        "## Model compatibility report",
        "",
        f"**Generated status:** `{report['status']}`",
        "",
        (
            "This report was generated by `trtvideo compatibility-report`. It may qualify "
            "for `community-reported`; it does not assign `validated` status."
        ),
    ]
    if report["errors"]:
        lines.extend(["", "### Errors", ""])
        lines.extend(f"- {error}" for error in report["errors"])
    if report["warnings"]:
        lines.extend(["", "### Warnings", ""])
        lines.extend(f"- {warning}" for warning in report["warnings"])

    lines.extend(
        [
            "",
            "### Model name and version",
            "",
            model["name"],
            "",
            "### Public model source",
            "",
            model["source"],
            "",
            "### Model license",
            "",
            model["license"],
            "",
            "### Source identity and tensor contract",
            "",
            _json_block(
                {
                    "source_format": model["source_format"],
                    "source_artifact": model["source_artifact"],
                    "tensor_contract": report.get("engine", {}).get("input"),
                    "output_contract": report.get("engine", {}).get("output"),
                    "scale": report.get("engine", {}).get("scale"),
                }
            ),
            "",
            "### Exact preparation and runtime commands",
            "",
        ]
    )
    commands = report.get("commands")
    if isinstance(commands, str):
        lines.extend(["```shell", commands, "```"])
    else:
        lines.append("Commands were omitted because command-log screening failed.")

    lines.extend(
        [
            "",
            "### Export conformance",
            "",
            _json_block(report["export_conformance"]),
            "",
            "### Engine sidecar",
            "",
            _json_block(report["engine"]),
            "",
            "### Environment and doctor",
            "",
            _json_block(
                {
                    "image": report["environment"]["image"],
                    "doctor": report["environment"]["doctor"],
                }
            ),
            "",
            "### Smoke test and output validation",
            "",
            _json_block(report["media"]),
            "",
            "### Submission checks",
            "",
            "- [x] The exact source artifact is identified without uploading model weights.",
            "- [x] Generated evidence contains no host filesystem paths or GPU UUIDs.",
            "- [x] I understand that this report does not automatically assign `validated`.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    os.replace(temporary, path)


def generate_compatibility_report(request: CompatibilityRequest) -> dict[str, Any]:
    """Collect, validate, sanitize, and persist one compatibility report."""
    try:
        request.output_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise CompatibilityEvidenceError(
            f"Cannot create report output directory: {request.output_dir.name}"
        ) from exc

    errors: list[str] = []
    warnings: list[str] = []
    source: dict[str, Any] = {}
    engine: dict[str, Any] = {}
    conformance: dict[str, Any] | None = None
    commands: str | None = None
    media: dict[str, Any] = {"valid": False, "errors": ["Media was not inspected"]}

    public_model = {"name": "[omitted]", "source": "[omitted]", "license": "[omitted]"}
    for field, value, label, validator in (
        ("name", request.model_name, "Model name", public_value),
        ("source", request.model_source, "Model source", _public_url),
        ("license", request.model_license, "Model license", public_value),
    ):
        try:
            public_model[field] = validator(value, label)
        except CompatibilityEvidenceError as exc:
            errors.append(str(exc))

    if request.source_format not in {"checkpoint", "onnx"}:
        errors.append("Source format must be checkpoint or onnx")
    if request.expected_frames <= 0:
        errors.append("Expected frame count must be greater than zero")
    try:
        source = file_identity(request.source_artifact)
    except CompatibilityEvidenceError as exc:
        errors.append(str(exc))

    model_spec = None
    try:
        engine, model_spec = engine_evidence(request.engine)
    except (CompatibilityEvidenceError, ValueError) as exc:
        errors.append(str(exc))

    try:
        commands = command_evidence(request.commands_file)
    except CompatibilityEvidenceError as exc:
        errors.append(str(exc))

    if request.source_format == "checkpoint":
        if request.export_conformance is None:
            errors.append("Checkpoint reports require export-conformance evidence")
        elif source and model_spec is not None:
            try:
                conformance = conformance_evidence(
                    request.export_conformance,
                    source_identity=source,
                    expected_scale=model_spec.scale,
                )
            except CompatibilityEvidenceError as exc:
                errors.append(str(exc))
    elif request.source_format == "onnx":
        if request.export_conformance is not None:
            errors.append("Existing ONNX reports must omit checkpoint export-conformance evidence")
        warnings.append(
            "Existing ONNX source has no checkpoint export-conformance evidence; "
            "the result can qualify only as community-reported"
        )

    try:
        doctor = run_doctor(gpu_id=request.gpu_id, disk_path=request.output_dir)
        doctor_data = _doctor_evidence(doctor)
    except Exception as exc:
        doctor_data = {"ready": False, "checks": []}
        errors.append(f"Doctor failed unexpectedly: {type(exc).__name__}")
    else:
        if not doctor.ready:
            errors.append("Static runtime doctor did not pass")

    if model_spec is not None and request.expected_frames > 0:
        try:
            input_inspection = inspect_media(
                request.input_video,
                collect_packets=False,
                full_decode=False,
            )
            output_inspection = inspect_media(
                request.output_video,
                collect_packets=True,
                full_decode=True,
            )
            media = validate_media(
                input_inspection,
                output_inspection,
                model=model_spec,
                expected_frames=request.expected_frames,
            )
        except (CompatibilityEvidenceError, CompatibilityMediaError) as exc:
            media = {"valid": False, "errors": [str(exc)]}
        if not media["valid"]:
            errors.append("Smoke-test output validation did not pass")

    image, image_errors = _image_evidence(request.image_reference)
    errors.extend(image_errors)
    report = {
        "document_type": "trtvideo-model-compatibility",
        "schema_version": REPORT_SCHEMA_VERSION,
        "status": "valid" if not errors else "invalid",
        "errors": errors,
        "warnings": warnings,
        "model": {
            **public_model,
            "source_format": request.source_format,
            "source_artifact": source,
        },
        "commands": commands,
        "export_conformance": conformance,
        "engine": engine,
        "environment": {
            "image": image,
            "gpu_id": request.gpu_id,
            "doctor": doctor_data,
        },
        "media": media,
        "request": {
            "expected_frames": request.expected_frames,
        },
        "generator": {
            "name": "trtvideo compatibility-report",
            "schema_version": REPORT_SCHEMA_VERSION,
        },
    }

    report_path = request.output_dir / "model-compatibility-report.json"
    markdown_path = request.output_dir / "model-compatibility-issue.md"
    markdown = render_issue_markdown(report)
    if len(markdown.encode("utf-8")) > _MAX_ISSUE_BODY_BYTES:
        report["commands"] = None
        errors.append("Generated issue body exceeded 60 KiB; command log was omitted")
        report["status"] = "invalid"
        markdown = render_issue_markdown(report)
    _write_text(report_path, json.dumps(report, indent=2, sort_keys=True) + "\n")
    _write_text(markdown_path, markdown)
    return {
        **report,
        "written_files": {
            "json": report_path,
            "markdown": markdown_path,
        },
    }
